name: Publish

permissions:
  id-token: write
  contents: read
  attestations: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  publish:
    name: Publish
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
          
      - name: Install Rust
        if: ${{ matrix.target == 'win-x64' }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Publish Windows
        if: ${{ matrix.target == 'win-x64' }}
        run: .\publish.ps1
        
      - name: Publish Linux
        if: ${{ matrix.target == 'linux-x64' }}
        run: ./publish.sh
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.kind }}
          path: artifacts/*
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Show files
        run: ls -R
      
      - name: Create Checksums
        run: ci/checksums.sh

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-checksums: artifacts/shasum.txt

      - name: Create Release Notes
        run: ci/release-notes.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body_path: release-notes.md
          files: |
            artifacts/min-ed-launcher*
            artifacts/shasum.txt          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
